# grants full access to the developer1 user within the development namespace by binding the developer-dev1-full-access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer1-full-access-binding
  namespace: development
subjects:
- kind: User
  name: developer1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-dev1-full-access
  apiGroup: rbac.authorization.k8s.io
